### ISSUE TITLE
ToastPackage Can't not found

### ISSUE THREAD

**Issue by Aofhero** [scttcper/ngx-toastr#173]
I try import 

> import {Toast, ToastPackage, ToastrService, ToastRef  } from 'ngx-toastr';

It error has no exported member 'ToastPackage'

Thanks.,

**Comment by scttcper** [comment]
I'm not able to reproduce. What version are you using?

**Comment by Aofhero** [comment]
Thanks for reply My version "ngx-toastr": "^6.0.1"

**Comment by scttcper** [comment]
remove your node_modules folder and reinstall. Its for sure in there.

**Comment by Aofhero** [comment]
Thank you very much

**Comment by Aofhero** [comment]
@scttcper Hi scttcper  Something wrong with GlobalConfig  When reinstall

` Can't resolve all parameters for AppComponent: ([object Object], [object Object], [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
	Error: Can't resolve all parameters for AppComponent: ([object Object], [object Object], [object Object], ?, [object Object], [object Object], [object Object], [object Object], [object Object], [object Object]).
	    at syntaxError (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:1550:34)
	    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:14887:35)
	    at CompileMetadataResolver._getTypeMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:14755:26)
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:14364:24)
	    at CompileMetadataResolver._getEntryComponentMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:15008:45)
	    at eval (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:14591:110)
	    at Array.map (<anonymous>)
	    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:14591:73)
	    at JitCompiler._loadModules (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:25640:66)
	    at JitCompiler._compileModuleAndComponents (http://localhost:5555/node_modules/@angular/compiler/bundles/compiler.umd.js:25599:52)
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js Report this error at https://github.com/liuy97/angular2-material-seed/issues`

**Comment by Aofhero** [comment]
Oh sorry my mistake, I remove GlobalConfig from constructor and work.
