### ISSUE TITLE
Base Class Implementation

### ISSUE THREAD

**Issue by paulstringerdb** [scttcper/ngx-toastr#205]
Hi,

Our *many* components all require a consistent approach to the display of Toastr notifications.
In some cases the same message etc...

We have tried to add a method in a base class to achieve this (and also tried in a service)... however... doing this seems to break toastr with the following error...

    at Overlay._createPaneElement (http://localhost:3030/webpack/TestHarness.js:27645:24)
    at Overlay.getPaneElement (http://localhost:3030/webpack/TestHarness.js:27632:54)
    at Overlay.create (http://localhost:3030/webpack/TestHarness.js:27622:44)
    at ToastrService._buildNotification (http://localhost:3030/webpack/TestHarness.js:28123:56)
    at ToastrService.success (http://localhost:3030/webpack/TestHarness.js:27960:21)
    at TestComponent.BaseItem.showSuccess (http://localhost:3030/webpack/TestHarness.js:27296:21)

Can you advise on the best way to incorporate this into a base class ?...

UPDATE

If I directly call the ".success('','')" method on the exposed base-class toastr instance from the derived class then the method works fine and displays correctly. It's only when using the method in the base class. Both on the same toastr instance???

**Comment by scttcper** [comment]
Please paste your custom toast if possible
