### ISSUE TITLE
Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.

### ISSUE THREAD

**Issue by wsh92** [scttcper/ngx-toastr#585]
Included BrowserAnimations correctly and followed all the steps in the Readme file, but still facing the same issue -->

![image](https://user-images.githubusercontent.com/37227370/48597437-c737f980-e92b-11e8-9437-b308e6d0cd45.png)

```
import { BrowserModule, DomSanitizer } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
imports: [
        BrowserModule,
        BrowserAnimationsModule]
})
```

FYI...I have implemented a custom toast component.

_Originally posted by @wsh92 in https://github.com/scttcper/ngx-toastr/issues/136#issuecomment-439276200_

**Comment by yarrgh** [comment]
Are you creating you're own custom component?

**Comment by wsh92** [comment]
> Are you creating you're own custom component?

Yes, I have created my own custom component. Here is the example I shared #348 to pass data to the custom component.
Also, click events are not working in the custom component. Not sure is it because of this error?

**Comment by SUtengda** [comment]
I have the same issue without creating own component

**Comment by ozkoidi** [comment]
I have the same issue but triggered by `Toast_HostBindings` when I run the unit tests.
I don't have a custom component and I don't use any animation in my application. I'm using:
- Angular 11.2.3
- ngx-toastr: 13.2.0

Do I need to include `NoopAnimationsModule `in the spec of every component that uses the `ToastrService`? Here is the error log:

```
Error: Found the synthetic property @flyInOut. Please include either "BrowserAnimationsModule" or "NoopAnimationsModule" in your application.
    at checkNoSyntheticProp (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2015/platform-browser.js:778:1)
    at DefaultDomRenderer2.setProperty (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/platform-browser/fesm2015/platform-browser.js:760:1)
    at elementPropertyInternal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:9970:1)
    at Module.ɵɵsyntheticHostProperty (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:18709:1)
    at Toast_HostBindings (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-toastr/fesm2015/ngx-toastr.js:934:39)
    at processHostBindingOpCodes (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:9182:1)
    at refreshView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:9460:1)
    at renderComponentOrTemplate (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:9528:1)
    at tickRootContext (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:10754:1)
    at detectChangesInRootView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2015/core.js:10779:1)```

**Comment by TimAndTyrion** [comment]
@ozkoidi You have to put your animations into your Component.  Some similar to should get you past that error.

@Component({
    selector: '[test-banner]',
    templateUrl: './test-banner.component.html',
    styleUrls: ['./test-banner.component.scss'],
    animations: [
        trigger('flyInOut', [
            transition(':enter', [
                style({transform: 'translateY(-100%)'}),
                animate('200ms ease-in', style({transform: 'translateY(0%)'}))
            ]),
            transition(':leave', [
                animate('200ms ease-in', style({transform: 'translateY(-100%)'}))
            ])
        ])
    ]
})

**Comment by Johncrown56** [comment]
If you're still looking for the solution, do the following;

1. Import BrowserAnimationsModule to your app.module.ts page. Like this below;
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

2. Add the module to your list of imports. Like this below;
imports: [
BrowserAnimationsModule
]


This should work perfectly.

**Comment by vivek185sensi** [comment]
> import { ToastrModule, ToastNoAnimation, ToastNoAnimationModule } from 'ngx-toastr';

@NgModule({
  imports: [
    // ...

    // BrowserAnimationsModule no longer required
    ToastNoAnimationModule.forRoot(),
  ],
  // ...
})
class AppModule {}

//this should fix your problem

**Comment by gsheeleypath** [comment]
@Johncrown56 That worked perfectly for me.  Thank you.

**Comment by amroosobhy** [comment]
Thanks your solution solved the issue
ToastNoAnimationModule.forRoot(),
but it comes in this format no color and in down-left corner not up-right!
![image](https://user-images.githubusercontent.com/82758753/210019330-6eb812cf-1ce8-4dd6-ad64-66a24bb85e4d.png)
