### ISSUE TITLE
NullInjectorError: No provider for ToastPackage!

### ISSUE THREAD

**Issue by alavaros** [scttcper/ngx-toastr#728]
I'm using ngx-toastr in another library which I add to my main application, but when I try to use the component, I get this error in the console:
```
ERROR Error: StaticInjectorError(AppModule)[AlertToastComponent -> ToastPackage]: 
  StaticInjectorError(Platform: core)[AlertToastComponent -> ToastPackage]: 
    NullInjectorError: No provider for ToastPackage!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1062)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveNgModuleDep (core.js:8369)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9057)
    at resolveDep (core.js:9422)
```
If I try to add it to the providers array, as suggested by the error, I get this other error when packing the library:
```
Building Angular Package
Building entry point '@mycompany/my-library'
Compiling TypeScript sources through ngc

: Can't resolve all parameters for toastPackage in C:/Path/to/my-library/node_modules/ngx-toastr/ngx-toastr.d.ts: (?, ?, ?, ?, ?, [object Object]).

BUILD ERRORError: : Can't resolve all parameters for toastPackage in C:/Path/to/my-library/node_modules/ngx-toastr/ngx-toastr.d.ts: (?, ?, ?, ?, ?, [object Object]).


    at Object.<anonymous> (C:\Path\to\my-library\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
: Can't resolve all parameters for toastPackage in C:/Path/to/my-library/node_modules/ngx-toastr/ngx-toastr.d.ts: (?, ?, ?, ?, ?, [object Object]).
    at fulfilled (C:\Path\to\my-library\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)

    at <anonymous>
Error: : Can't resolve all parameters for toastPackage in C:/Path/to/my-library/node_modules/ngx-toastr/ngx-toastr.d.ts: (?, ?, ?, ?, ?, [object Object]).

    at Object.<anonymous> (C:\Path\to\my-library\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Path\to\my-library\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>
```
I don't know what I'm missing, this is part of my component:
```
...
import { Toast, ToastPackage, ToastrService } from 'ngx-toastr';
...
export class AlertToastComponent extends Toast implements OnInit {
...
  constructor(
    protected toastrService: ToastrService,
    public toastPackage: ToastPackage,
  ) {
    super(toastrService, toastPackage);
  }
...
}
```
Then, in the library module I have:
```
...
import { ToastContainerModule, ToastrModule } from 'ngx-toastr';
import { AlertToastContainerComponent } from './components/alert-toast-container/alert-toast-container.component';
import { AlertToastComponent } from './components/alert-toast/alert-toast.component';
import { AlertToastService } from './services/alert-toast/alert-toast.service';
...
@NgModule({
...
  imports: [
    ...
    ToastrModule.forRoot({
      positionClass: 'inline',
      toastComponent: AlertToastComponent,
      timeOut: 4000,
      enableHtml: true,
    }),
    ToastContainerModule,
  ],
  entryComponents: [
    AlertToastComponent,
  ],
  declarations: [
    ...
    AlertToastComponent,
    AlertToastContainerComponent,
    ...
  ],
  exports: [
    ...
    AlertToastComponent,
    AlertToastContainerComponent,
    ...
  ],
  providers: [
    AlertToastService,
  ],
```
Do I need to import/export ToastPackage?

**Comment by shailendrakumarsaini** [comment]
I have same issue 
To fix this issue I just installed ngx-toast based on  this
![image](https://user-images.githubusercontent.com/25609682/111478521-29040a80-8756-11eb-9393-8b7d1bf94b69.png)
