### ISSUE TITLE
 Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by rojasjuniore** [scttcper/ngx-toastr#734]
Hello when compiling, I get the following error:

```
Angular CLI: 8.0.3
Node: 12.4.0
OS: darwin x64
Angular: 8.1.0-next.1
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
```

`Version: "ngx-toastr": "^11.2.0",
`
`node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng b --prod --aot=true --build-optimizer=true`

> ERROR in ./node_modules/ngx-toastr/fesm5/ngx-toastr.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:265:35)
    at checkNodeForDecorators (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:77:21)
    at visitNodes (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16514:30)
    at Object.forEachChild (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16740:24)
    at checkNodeForDecorators (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16635:21)
    at checkNodeForDecorators (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16692:24)
    at checkNodeForDecorators (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16703:24)
    at checkNodeForDecorators (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/src/transforms/scrub-file.js:68:31)
    at visitNode (/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16505:24)
    at Object.forEachChild `(/Users/Guest/Project/settle/frontend/SETTLE-WLDC/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:16599:21)`

**Comment by scttcper** [comment]
weird version of angular `Angular: 8.1.0-next.1` use a final version like `8.2.13`
