### ISSUE TITLE
Cannot instantiate cyclic dependency! ApplicationRef ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot instantiate cyclic dependency! ApplicationRef with Angular 9

### ISSUE THREAD

**Issue by williamdes** [scttcper/ngx-toastr#804]
```
Prerendering 5 route(s) to projectName/dist/browser
Unhandled Promise rejection: Cannot instantiate cyclic dependency! ApplicationRef ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot instantiate cyclic dependency! ApplicationRef
    at throwCyclicDependencyError (projectName/dist/server/main.js:1:2263474)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263534)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.Overlay_Factory [as factory] (projectName/dist/server/main.js:1:462926)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ToastrService_Factory [as factory] (projectName/dist/server/main.js:1:469948)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at Object.ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ErrorService_Factory [as factory] (projectName/dist/server/main.js:1:1163807)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at injectArgs (projectName/dist/server/main.js:1:2150440)
    at Object.factory (projectName/dist/server/main.js:1:2266772)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ApplicationModule_Factory [as factory] (projectName/dist/server/main.js:1:2551547)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at projectName/dist/server/main.js:1:2260913
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (projectName/dist/server/main.js:1:2260891)
    at new NgModuleRef$1 (projectName/dist/server/main.js:1:2438708)
    at NgModuleFactory$1.create (projectName/dist/server/main.js:1:2439700)
    at projectName/dist/server/main.js:1:2497637
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996670)
    at Object.onInvoke (projectName/dist/server/main.js:1:2488384)
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996566)
    at Zone.run (projectName/dist/server/main.js:1:1989084)
    at NgZone.run (projectName/dist/server/main.js:1:2489301)
    at PlatformRef.bootstrapModuleFactory (projectName/dist/server/main.js:1:2497488)
    at projectName/dist/server/main.js:1:2498753
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996670)
    at Zone.run (projectName/dist/server/main.js:1:1989084)
    at projectName/dist/server/main.js:1:2008181
    at ZoneDelegate.invokeTask (projectName/dist/server/main.js:1:1997602)
    at Zone.runTask (projectName/dist/server/main.js:1:1990167)
    at drainMicroTaskQueue (projectName/dist/server/main.js:1:2001210) Error: Cannot instantiate cyclic dependency! ApplicationRef
    at throwCyclicDependencyError (projectName/dist/server/main.js:1:2263474)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263534)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.Overlay_Factory [as factory] (projectName/dist/server/main.js:1:462926)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ToastrService_Factory [as factory] (projectName/dist/server/main.js:1:469948)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at Object.ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ErrorService_Factory [as factory] (projectName/dist/server/main.js:1:1163807)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at injectArgs (projectName/dist/server/main.js:1:2150440)
    at Object.factory (projectName/dist/server/main.js:1:2266772)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at injectInjectorOnly (projectName/dist/server/main.js:1:2149058)
    at ɵɵinject (projectName/dist/server/main.js:1:2149224)
    at Object.ApplicationModule_Factory [as factory] (projectName/dist/server/main.js:1:2551547)
    at R3Injector.hydrate (projectName/dist/server/main.js:1:2263620)
    at R3Injector.get (projectName/dist/server/main.js:1:2260350)
    at projectName/dist/server/main.js:1:2260913
    at Set.forEach (<anonymous>)
    at R3Injector._resolveInjectorDefTypes (projectName/dist/server/main.js:1:2260891)
    at new NgModuleRef$1 (projectName/dist/server/main.js:1:2438708)
    at NgModuleFactory$1.create (projectName/dist/server/main.js:1:2439700)
    at projectName/dist/server/main.js:1:2497637
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996670)
    at Object.onInvoke (projectName/dist/server/main.js:1:2488384)
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996566)
    at Zone.run (projectName/dist/server/main.js:1:1989084)
    at NgZone.run (projectName/dist/server/main.js:1:2489301)
    at PlatformRef.bootstrapModuleFactory (projectName/dist/server/main.js:1:2497488)
    at projectName/dist/server/main.js:1:2498753
    at ZoneDelegate.invoke (projectName/dist/server/main.js:1:1996670)
    at Zone.run (projectName/dist/server/main.js:1:1989084)
    at projectName/dist/server/main.js:1:2008181
    at ZoneDelegate.invokeTask (projectName/dist/server/main.js:1:1997602)
    at Zone.runTask (projectName/dist/server/main.js:1:1990167)
    at drainMicroTaskQueue (projectName/dist/server/main.js:1:2001210)
```

**Comment by williamdes** [comment]
```diff
diff --git a/src/app/shared/error/error.service.ts b/src/app/shared/error/error.service.ts
index d09d050ca..2e8fb6cde 100644
--- a/src/app/shared/error/error.service.ts
+++ b/src/app/shared/error/error.service.ts
@@ -1,5 +1,5 @@
 import { HttpErrorResponse } from '@angular/common/http';
-import { ErrorHandler, Injectable } from '@angular/core';
+import { ErrorHandler, Injectable, Inject, Injector } from '@angular/core';
 import { ToastrService } from 'ngx-toastr';
@@ -25,11 +25,16 @@ interface ErrorFromApi {
 export class ErrorService implements ErrorHandler {
 
     constructor(
-        // private _toastrService: ToastrService,
+        @Inject(Injector) private injector: Injector,
         private _translateService: TranslateService
     ) { }
 
+    // Need to get ToastrService from injector rather than constructor injection to avoid cyclic dependency error
+    private get _toastrService(): ToastrService {
+        return this.injector.get(ToastrService);
+    }
+
     handleError(error): void {
 
-        /*this._toastrService[type](options.text, null, {
+        this._toastrService[type](options.text, null, {
             timeOut,
             positionClass: 'toast-top-center',
             easeTime: 150,
             enableHtml: true,
             closeButton: true,
-        });*/
+        });
     }
 
 }
```

**Comment by williamdes** [comment]
Inspired from https://github.com/scttcper/ngx-toastr/issues/179#issuecomment-325724269

**Comment by williamdes** [comment]
Solved, I posted here for the record.
