### ISSUE TITLE
Jest issue ToastrModule which does not have a ɵmod property

### ISSUE THREAD

**Issue by srinidoppalapudi** [scttcper/ngx-toastr#907]
Importing ToastrModule which does not have a ɵmod property

      at ../packages/core/src/render3/jit/module.ts:491:13 [ProxyZone]
          at Array.forEach (<anonymous>) [ProxyZone]
      at transitiveScopesFor (../packages/core/src/render3/jit/module.ts:484:30) [ProxyZone]
      at ../packages/core/src/render3/jit/module.ts:496:27 [ProxyZone]
          at Array.forEach (<anonymous>) [ProxyZone]
      at transitiveScopesFor (../packages/core/src/render3/jit/module.ts:484:30) [ProxyZone]
      at setScopeOnDeclaredComponents (../packages/core/src/render3/jit/module.ts:414:28) [ProxyZone]
      at Object.flushModuleScopingQueueAsMuchAsPossible [as ɵflushModuleScopingQueueAsMuchAsPossible] (../packages/core/src/render3/jit/module.ts:60:11) [ProxyZone]
      at TestBedRender3.Object.<anonymous>.TestBedRender3.checkGlobalCompilationFinished (../packages/core/testing/src/r3_test_bed.ts:409:7) [ProxyZone]
      at TestBedRender3.Object.<anonymous>.TestBedRender3.resetTestingModule (../packages/core/testing/src/r3_test_bed.ts:237:10) [ProxyZone]
      at Function.Object.<anonymous>.TestBedRender3.resetTestingModule (../packages/core/testing/src/r3_test_bed.ts:186:26) [ProxyZone]
      at ../packages/core/testing/src/before_each.ts:25:13 [ProxyZone]
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:292:43) [ProxyZone]
      at Object.<anonymous> (node_modules/jest-zone-patch/index.js:50:27) [ProxyZone]
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:292:43) [ProxyZone]
      at Object.<anonymous> (node_modules/zone.js/dist/zone-testing.js:750:34) [<root>]
      at processTicksAndRejections (internal/process/task_queues.js:93:5) [<root>]

**Comment by MaximeKoitsalu** [comment]
Have the exact same issue, 14.2.0 seems broken. I recommend reverting to 14.1.4 until a fix is released
